# html lang
language: en

menuname: Luna's Blog

# Your Name
author: Luna

# main menu navigation
menu:
  About👀: /about
  Home🎃: http://tanger.cloud/
  GitHub🧨: https://github.com/redhat123456

topmenu:
  Main: /
  about: /about

## 웹 설명
description: 

## 사이트키워드: 영어 쉼표로 구분
keywords: hexo,theme,MiHoYo

## blog 프로필사진
img_src: https://KuraiLuna.github.io/images/lumine.png

# Title
logo_title: Luna's Developer Diary

# Your Slogan
words: printf("Hello World!");

# 위쪽 테두리 슬라이드
# topmenu:
# 홈 index:/
# about: /about 정보

# stylesheets loaded in the <head>
stylesheets:
  - /css/MiHoYo.css

# scripts loaded in the end of the body
scripts:
  - /js/MiHoYo.js

# 리뷰 시스템 | Comments
## 도메인 제한을 했습니다, 자신의 KEY로 변경해 주세요.
## valine을 끄면 enable을 false로 설정합니다
valine:
  enable: false
  appId:
  appKey:
